services:
  db:
    image: postgres:16
    container_name: restaurant_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: restaurant_app
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: 90ab7c244a156c04f99dbd757d4e321f5cf120f7804afb5cb0fc2fb7324d15fa
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/restaurant_db
      TEST_DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/test_restaurant_db
    depends_on:
      - db
    
  redis:
    image: redis:7
    container_name: redis_restaurant_app
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: